In [3]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

In [5]:
true_w = torch.tensor([1.1, -0.9, 1])
true_b = 3.8
X, y = d2l.synthetic_data(true_w, true_b, 1000)

In [7]:
batch_size = 10
def load_array(data_array, batch_size, is_train=True):
    dataset = data.TensorDataset(*data_array)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

data_iter = load_array((X, y), batch_size)

In [8]:
next(iter(data_iter))

[tensor([[ 0.3017,  0.4695,  0.4006],
         [ 1.1771, -0.5304, -0.2840],
         [-1.7897, -0.0280,  1.5818],
         [ 0.8929, -0.8784,  1.2134],
         [ 0.8289,  0.7091,  1.3910],
         [-0.9304,  1.0064,  2.3819],
         [ 0.3999,  0.5270,  0.1890],
         [-1.8918, -1.3494,  0.1407],
         [-0.1202, -0.2999, -0.4350],
         [ 0.3071, -1.6727, -0.3351]]),
 tensor([[4.1033],
         [5.2843],
         [3.4197],
         [6.7921],
         [5.4653],
         [4.2542],
         [3.9422],
         [3.0781],
         [3.5089],
         [5.3105]])]

In [9]:
from torch import nn
net = nn.Sequential(nn.Linear(3,1))
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [10]:
loss = nn.MSELoss()

In [12]:
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

In [13]:
num_epochs = 10
for epoch in range(num_epochs):
    for batch_X, batch_y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(X), y)
    print(f'epoch {epoch}, loss {l:f}')

epoch 0, loss 0.000228
epoch 1, loss 0.000098
epoch 2, loss 0.000098
epoch 3, loss 0.000098
epoch 4, loss 0.000098
epoch 5, loss 0.000098
epoch 6, loss 0.000098
epoch 7, loss 0.000098
epoch 8, loss 0.000098
epoch 9, loss 0.000098


In [14]:
net[0].weight.data

tensor([[ 1.1000, -0.8997,  1.0002]])

In [15]:
net[0].bias.data

tensor([3.7995])